/** @type {import('stylelint').Config} */
export default {
  extends: "stylelint-config-standard",
};
module.exports = {
  customSyntax: 'postcss-scss',
  extends: ['stylelint-config-standard', 'stylelint-config-taro-rn'],
  rules: {
    'selector-max-id': 0,
    'selector-max-type': 0,
    'selector-max-attribute': 0,
    'color-named': 'never',
    'color-hex-length': 'long',
    'color-no-invalid-hex': true,
    'comment-no-empty': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'font-family-name-quotes': 'always-where-recommended',
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'font-weight-notation': 'named-where-possible',
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-url-quotes': 'always',
    'function-no-unknown': null,
    'alpha-value-notation': 'number',
    'color-function-notation': 'legacy',
    'keyframe-declaration-no-important': true,
    'media-feature-name-no-unknown': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': null,
    'no-invalid-double-slash-comments': true,
    'selector-attribute-quotes': 'always',
    'string-no-newline': true,
    'selector-no-vendor-prefix': null,
    'selector-class-pattern': null,
    'selector-max-combinators': null,
    'taro-rn/line-height-no-value-without-unit': null,
    'at-rule-no-unknown': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'import-notation': 'string',
    'taro-rn/css-property-no-unknown': null,
    'taro-rn/font-weight-no-ignored-values': null,
    'selector-pseudo-class-allowed-list': null,
  },
}
